name: PR

on:
  pull_request:
    branches:
    - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Build solution
        run: npm run build